@url_base = http://localhost:5268/api/aluno

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NDk5OTUyMTN9.bAvU_-E8sIgZyyycInXsWykEtQFA0i7aga_6KEs61tQ


### Cadastrar aluno
POST {{url_base}}/cadastrar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome" : "filipe",
    "email" : "filipe@gmail.com"
}

### Listar aluno
GET {{url_base}}/listar
Authorization: Bearer {{token}}