@url_base = http://localhost:5268/api/aluno

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NTAwMTczNzJ9.55K5xklCu0iVzeYW4zeD3kjQI1YMy28lP__DAFgO55o

### 1. Cadastrar Aluno (requer role admin)
POST {{url_base}}/cadastrar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "cecilia2",
    "email": "cecilia_love@email.com",
    "senha": "123456",
    "matricula": "202020"
}

### 2. Listar Alunos (requer autenticação)
GET {{url_base}}/listar
Authorization: Bearer {{token}}

### 3. Buscar Aluno por ID (requer autenticação)
GET {{url_base}}/1
Authorization: Bearer {{token}}

### 4. Vincular Aluno à Disciplina (requer role admin)
POST {{url_base}}/vincular-disciplina
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "alunoId": 4,
    "disciplinaId": 1
}

