@url_base = http://localhost:5268/api/aluno

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdGVAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NDY5MzMzNTR9.7KbPiQKPYOSPwaxKmKwN3ebvR2cTzGFVeaAjBJbFpO8
POST {{url_base}}/cadastrar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome" : "cecilia",
    "email" : "cecilia@gmail.com"
}

### Listar aluno
GET {{url_base}}/listar
Authorization: Bearer {{token}}