@url_base = http://localhost:5268/api/disciplina

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NTM1NTU3ODJ9.O4eA9M_hvoI2sAiHSUEH5hb1txbFhbjgE-bycszhAmI


### 1. Cadastrar Disciplina (requer role admin)
POST {{url_base}}/cadastrar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "c#"
}

### 2. Listar Disciplinas (requer autenticação)
GET {{url_base}}/listar
Authorization: Bearer {{token}}

### 3. Buscar Disciplina por ID (requer autenticação)
GET {{url_base}}/1
Authorization: Bearer {{token}}

### 4. Atualizar Disciplina (requer role admin)
PUT {{url_base}}/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Matemática atualizada"
}

### 5. Deletar Disciplina (requer role admin)
DELETE {{url_base}}/4
Authorization: Bearer {{token}}