@url_base = http://localhost:5268/api/professor


### Gerar token d professor
POST {{url_base}}/gerar-token
Content-Type: application/json

{
    "email": "joao@email.com",
    "senha": "123456"
}

### Cadastrar professor
POST {{url_base}}/cadastrar
Content-Type: application/json

{
    "nome" : "Professor Admin",
    "email" : "admin@email.com",
    "senha" : "123456",
    "role" : "admin"
}

### Login
POST {{url_base}}/login
Content-Type: application/json

{
    "email" : "admin@email.com",
    "senha" : "123456"
}

### Listar professores
GET {{url_base}}/listar
