@url_base = http://localhost:5268/api/professor
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5AZW1haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJleHAiOjE3NDk5OTc0Nzl9.LLu_2W12qhbL2tLNK67Scs_elinWkV-IjGWWgRCvF1Y

### 1. Cadastrar Professor (Admin)
POST {{url_base}}/cadastrar
Content-Type: application/json

{
    "nome": "Professor Admin",
    "email": "admin@email.com",
    "senha": "123456",
    "role": "admin"
}

### 4. Login como Professor
POST {{url_base}}/login
Content-Type: application/json

{
    "email": "admin@email.com",
    "senha": "123456"
}

### 5. Listar Professores (requer autenticação)
GET {{url_base}}/listar
Authorization: Bearer {{token}}
