@url_base = http://localhost:5268/api/turma

### Login como Professor (Admin)
GET {{url_base}}/listar
Content-Type: application/json


### Login como Aluno
POST {{url_base}}/login
Content-Type: application/json

{
    "email": "cecilia_love@email.com",
    "senha": "123456"
} 