@url_base = http://localhost:5268/api/usuario

### Cadastrar usuário
POST {{url_base}}/cadastrar
Content-Type: application/json

{
    "nome" : "teste",
    "email" : "teste@gmail.com",
    "senha" : "123",
    "role" : "admin"
}

### Login
POST {{url_base}}/login
Content-Type: application/json

{
    "nome" : "teste",
    "email" : "teste@gmail.com",
    "senha" : "123",
    "role" : "admin"
}

### Listar usuários
GET {{url_base}}/listar
