@url_base = http://localhost:5268/api/aluno

### Cadastrar aluno
POST {{url_base}}
Content-Type: application/json

{
    "nome": "João Silva",
    "email": "joao@email.com",
    "senha": "123456",
    "permissao": 1
}

### Listar alunos
GET {{url_base}}
